### ISSUE TITLE
Can this be used reliably on desktop as well?

### ISSUE THREAD

**Issue by gebrits** [BR0kEN-/jTap#3]
It would be great to have a unified solution for mobile (`touch`) and desktop (`click`). Can this be used?

**Comment by BR0kEN-** [comment]
You can attach handlers in this way and they will works fine on desktops and touch devices.
```javascript
$('#element').on('tap', handler);
```

In last paragraph of [usage](https://github.com/BR0kEN-/jTap#usage) section of the documentation you can read about that fact.

Also, in [code](https://github.com/BR0kEN-/jTap/blob/master/plugin/jquery.tap.js#L17-L18) of the library you can see that "mousedown" and "mouseup" events was binded.
