### ISSUE TITLE
Tapping re-taps element behind what was tapped

### ISSUE THREAD

**Issue by sgiacinto** [BR0kEN-/jTap#6]
Tapping an element, i.e. a close button, causes the element behind it which is made visible by the close, to receive the tap event as well.

**Comment by BR0kEN-** [comment]
@sgiacinto, could you provide example (HTML+CSS) to make me able to reproduce correctly?

**Comment by sgiacinto** [comment]
Sorry, my mistake - I downloaded an old version. Please resolve this as a non-issue. It works perfect!
